# Site setings
name: "John"
description: "Software developer based out of Nairobi"
meta_description: "Software developer based out of Nairobi"
logo: "assets/images/logo-jp.png"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: "https://jpmulongo.me"
disqus:
mailchimp_url:
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-136524653-1

# Author
author:
  name: "John Paul Mulongo"
  image: "jp-profile.jpeg"
  greetings: "Hi there!"
  description: "My name is John Paul Mulongo. I'm a software developer based in Nairobi."
  bio:

# Contact form setings
email: mulongojohnpaul@gmail.com
contact_page_description:
thankyou_page_description:

# Social links
# twitter: "username"
github: "Omulosi"
linkedin: "jp-mulongo"
# codepen: "username"

# Custom collections - enable looping through a list of projects
collections:
  projects:
    output: true

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Blog
    url: /blog/
  - text: Projects
    url: /projects/
  - text: Now
    url: /now/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /blog/page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
